<?php

namespace App\Traits;

trait FillableTraits
{
    protected array $users = [

    ];

    protected array $bookings = [
        'region_id',
        'driver_id',
        'customer_id',
        'payment_detail',
        'fee',
        'reference',
        'pick_up_date',
        'pick_up_time',
        'drop_off_date',
        'drop_off_time',
        'pick_location',
        'drop_off_location',
        'status',
        'payment_status',
        'payment_method',
        'pick_up_lat',
        'pick_up_lng',
        'drop_off_lat',
        'drop_off_lng',

        'car_id',
        'completed',
        'cancelled',
        'rating',
        'rating_comment',


        'extra_time_price',

        'discount',
        'tax',
        'grand_total',

        'rental_id',

        'booking_type',
        'driver_earn',
        'commission',
        'cancellation_reason',
        'cancelled_by',
        'comment',
        'picked',

        'booking_number',
        'confirmation_no',
        'is_confirmed',
        'insurance_fee',
        'insurance_coverage',
        'deposit_fee',
        'company_id',

        'extras',
        'booking_period',
        'billing_details',
    ];

    protected array $car_extra = [
        'is_taxed',
        'car_id',
        'mots',
        'tax_expiry_date',
        'tax_amount',
        'tax_type',
        'service',
        'documents',
        'subscriptions',
        'finance',
        'damage_history',
        'repairs',
    ];

    protected array $car = [
        'driver_id',
        'title',
        'make',
        'model',
        'type',
        'year',
        'color',
        'gear',
        'door',
        'vehicle_no',
        'region_id',
        'is_available',

        'rental_packages',
        'image',
        'company_id',

        'country',
        'state',
        'city',
        'price_per_day',
        'attributes',
        'photos',
        'youtube_link',

        'deposit',
        'bags',
        'bags_large',
        'cancellation_fee',
        'price_per_mileage',
        'mileage',
        'requirements',
        'security_deposit',
        'damage_excess',
        'insurance_fee',
        'mileage_text',
        'insurance_coverage',
        'important_text',
        'air_condition',
        'seats',
        'extras',
        'drop_off_instruction',
        'pickup_instruction',

        'engine_size',
        'fuel_type',
        'body_type',

        'license_no',
        'tracker_no',
        'description',
        'registration_number',
        'driver',
        'commission_fee',

        'daily_rate',
        'weekly_rate',
        'monthly_rate',
        'dynamic_pricings',

        'is_approved',
        'mileage_policy',
        'mileage_limit',
        'excess_mileage_rate',
        'cancellation_policy',
        'vehicle_photos',

        'private_hire',
        'licensing_authority',
        'phv_plate_number',
        'phv_expiry_date',
        'hr_insurance_expiry',
        'plate_certificate',
        'hr_insurance_proof',
        'short_term',
        'long_term',
        'rent_to_buy',
        'short_term_minimum_term',
        'short_term_maximum_term',
        'short_term_pricing_cadence',
        'short_term_weekly_price_wo_ins',
        'short_term_weekly_price_w_ins',
        'short_term_maintenance_included',
        'short_term_deposit',
        'short_term_excess_liability',
        'short_term_early_return_fee',
        'short_term_notice_period_to_return',
        'long_term_billing_cycle',
        'long_term_default_deposit',
        'long_term_term_options',
        'long_term_prices',
        'long_term_excess_liability',
        'long_term_vehicle_swap_allowed',
        'long_term_early_termination_rules',
        'rent_to_buy_term',
        'rent_to_buy_billing_cycle',
        'rent_to_buy_price_per_cycle',
        'rent_to_buy_deposit_amount',
        'rent_to_buy_balloon_payment',
        'rent_to_buy_payment_break_weeks_year',
        'rent_to_buy_mileage_allowance_per_cycle',
        'rent_to_buy_excess_mileage_rate',
        'rent_to_buy_insurance_included',
        'rent_to_buy_maintenance_included',
        'rent_to_buy_ev_incentive_included',
        'rent_to_buy_ownership_transfer_notes',
        
        'top_pick',
        'ideal_for_family',
        
        'pickup',
        'dropup',
        
        'free_cancellation',
        'collision_damage_waiver',
        'theft_protection',
        'unlimited_mileage',
        
        'vehicle_features',
        'daily_rate_tax_incl',
        'weekly_rate_tax_incl',
        'monthly_rate_tax_incl',
    ];

    protected array $user = [
        'first_name',
        'last_name',
        'avatar',
        'email',
        'phone',
        'is_online',
        'map_lat',
        'map_lng',
        'email_verified_at',
        'password',
        'pass',
        'comment',
        'status',
        'address',
        'country_code',
        'country',
        'city',
        'region_id',
        'service_id',
        'company_id',
        'push_token',
        'last_notification',
        'monify_account',
        'referral',
        'gender',
        'ride_status',
        'last_location_update',

        'work_phone',
        'hire_type',
        'address_2',
        'postcode',
        'contact_name',
        'phone_number',
        'email_address',
        'relationship',
    ];

    protected array $trip_request = [
        'region_id',
        'driver_id',
        'temp_driver_id',
        'customer_id',
        'fee',
        'reference',
        'origin',
        'destination',
        'status',
        'payment_status',
        'payment_method',
        'origin_lat',
        'origin_lng',
        'destination_lat',
        'destination_lng',
        'started_at',
        'end_at',
        'current_lat',
        'current_lng',
        'distance',
        'distance_text',
        'duration',
        'duration_text',
        'car_id',
        'completed',
        'cancelled',
        'rating',
        'driver_rating',
        'rating_comment',
        'driver_rating_comment',
        'driver_feedback',
        'rider_feedback',
        'base_price',
        'time_price',
        'distance_price',
        'discount',
        'tax',
        'grand_total',
        'service_id',
        'ride_type',
        'scheduled',
        'driver_earn',
        'commission',
        'cancellation_reason',
        'cancelled_by',
    ];

    protected array $pcns = [
        'car_id',
        'booking_id',
        'vrm',
        'pcn_no',
        'date_time',
        'offence_type',
        'location',
        'notice_issue_date',
        'payment_dead_line',
        'appeal_dead_line',
        'status',
        'histories',

        'date_of_contravention',
        'deadline_date',
        'issuing_authority',
        'priority',
        'notes',

        'linkup_with_driver',
        'linkup_with_vehicle_registration_no',
        'notify_to_driver',
        'notify_to_staff_member',
        'notify_to_other',
        'reminder'

    ];
}
